// This file is automatically generated by the Firebase setup script.
// Do not edit this file manually, as it will be overwritten.

export const firebaseConfig = {
  "apiKey": "API_KEY",
  "authDomain": "AUTH_DOMAIN",
  "projectId": "PROJECT_ID",
  "storageBucket": "STORAGE_BUCKET",
  "messagingSenderId": "MESSAGING_SENDER_ID",
  "appId": "APP_ID"
};
