
// This file is automatically generated by the Firebase setup script.
// Do not edit this file manually, as it will be overwritten.

export const firebaseConfig = {
  "projectId": "studio-2586101103-d236f",
  "appId": "1:994281137308:web:e9e2f420f6c77730faf959",
  "apiKey": "AIzaSyCNY3a4sU1zUk-2LDpCZ0maWvDpsYfcmzs",
  "authDomain": "studio-2586101103-d236f.firebaseapp.com",
  "measurementId": "",
  "storageBucket": "studio-2586101103-d236f.appspot.com",
  "messagingSenderId": "994281137308"
};
